language: python
sudo: true
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

before_install:
  - export DEBUG=false
  - export TEST=true

install:
  - pip install -r requirements.txt
  - pip install python-memcached codecov pytest-django pytest-cov
  - python manage.py makemigrations
  - python manage.py migrate

script:

  - pytest --cov=.

after_success:
- codecov